export const API_CONFIG = {
    BASE_URL: process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8080",
    HEALTH_URL: "http://localhost:8080/health",
    ENDPOINTS: {
        AUTH: {
            LOGIN: '/api/v1/auth/login',
            REGISTER: '/api/v1/auth/signup',
            REFRESH_TOKEN: '/api/v1/auth/refresh-token',
            LOGOUT: '/api/v1/auth/logout',
            OAUTH: {
                GOOGLE: "/api/v1/auth/oauth2/google",
                GITHUB: "/api/v1/auth/oauth2/github",
              },
            
            CURRENT_USER: '/api/v1/auth/current-user',
            VERIFY_EMAIL: '/api/v1/auth/verify-email',
            RESEND_VERIFICATION: '/api/v1/auth/resend-verification',
            SETUP_2FA: '/api/v1/auth/setup-2fa',
            VERIFY_2FA: '/api/v1/auth/verify-2fa',
            DISABLE_2FA: '/api/v1/auth/disable-2fa',
        },
        NOTIFICATIONS: {
            WS: '/api/notifications/ws',
            LIST: '/api/notifications',
            SEND: '/api/notifications',
            PREFERENCES: '/api/notifications/preferences',
            MARK_READ: (id: number) => `/api/notifications/${id}/read`,
        },
        DEVICE_MANAGEMENT: {
            LIST: '/api/devices',
            REGISTER: '/api/devices/register',
            DETAIL: (deviceId: string) => `/api/devices/${deviceId}`,
            ACTIVITY: (deviceId: string) => `/api/devices/${deviceId}/activity`,
            UPDATE_STATUS: (deviceId: number) => `/api/v1/devices/update-status/${deviceId}`
        },
        THREATS: {
            DATA: '/api/threats/data',
            FEATURES: '/api/threats/features',
            TYPES: '/api/threats/threat-types',
            CURRENT: '/api/threats/current-threats',
            USER: (userId: string) => `/api/threats/user/${userId}`,
            DEVICE: (deviceId: number) => `/api/threats/device/${deviceId}`,
            IP: (ipAddress: string) => `/api/threats/ip/${ipAddress}`,
            MANUAL_DETECTION: "/api/threats/manual-detection",
            TIME_RANGE: "/api/threats/time-range",
            SEVERITY: (severity: string) => `/api/threats/severity/${severity}`,
        },
        INCIDENTS: {
            LOGS: '/api/incidents/logs',
            SEVERITY: '/api/incidents/severity',
            METRICS: '/api/incidents/metrics',
        },
        REPORTS: {
            SUMMARY: '/api/reports/summary',
            DETAILED: (threatId: number) => `/api/reports/detailed/${threatId}`,
            EXPORT_PDF: (threatId: number) => `/api/reports/export/pdf/${threatId}`,
            EXPORT_CSV: (threatId: number) => `/api/reports/export/csv/${threatId}`,
            INTEGRATED_REPORT: '/api/reports/integration/enriched',
            PERMISSION: '/api/reports/integration/permission',
        },
        USER_MANAGEMENT: {
            REGISTER: '/api/v1/user-management/register',
            GET_USER_BY_ID: (userId: number) => `/api/v1/user-management/${userId}`,
            UPDATE_USER: (userId: number) => `/api/v1/user-management/${userId}`,
            FIND_USER_BY_EMAIL: '/api/v1/user-management/email',
            CHECK_SUBSCRIPTION: (userId: number) => `/api/v1/user-management/${userId}/subscription`,
            CHECK_2FA: (userId: number) => `/api/v1/user-management/${userId}/2fa`,
            REGISTER_DEVICE: (userId: number) => `/api/v1/user-management/${userId}/device/register`,
            HANDLE_SUSPICIOUS_ACTIVITY: (userId: number) => `/api/v1/user-management/${userId}/suspicious-activity`,
            GET_USER_PROFILE: (userId: number) => `/api/v1/user-management/profile/${userId}`,
            UPDATE_PROFILE: (userId: number) => `/api/v1/user-management/profile/${userId}`,
            ENABLE_2FA: (userId: number) => `/api/v1/user-management/profile/${userId}/2fa/enable`,
            DELETE_ACCOUNT: (userId: number) => `/api/v1/user-management/profile/${userId}`,
            GET_AUDIT_LOGS: (userId: number) => `/api/v1/user-management/profile/${userId}/audit-logs`,
            GET_RECENT_LOGS: (userId: number) => `/api/v1/user-management/profile/${userId}/recent-logs`,
            UPDATE_ATTRIBUTE: (userId: number, attributeName: string) => `/api/v1/user-management/${userId}/attributes/${attributeName}`,
            GET_ATTRIBUTE: (userId: number, attributeName: string) => `/api/v1/user-management/${userId}/attributes/${attributeName}`,
            DELETE_ATTRIBUTE: (userId: number, attributeName: string) => `/api/v1/user-management/${userId}/attributes/${attributeName}`,
            UPDATE_SECURITY_STATUS: (userId: number) => `/api/v1/user-management/${userId}/security-status`,
            GET_SECURITY_STATUS: (userId: number) => `/api/v1/user-management/${userId}/security-status`,
            GET_DEVICES: (userId: number) => `/api/v1/user-management/${userId}/devices`,
            LOG_ACTIVITY: (userId: number) => `/api/v1/user-management/${userId}/activities`,
            OAUTH2_REGISTER: '/api/v1/user-management/oauth2/register',
            OAUTH2_LOGIN: '/api/v1/user-management/oauth2/login',
            LOG_DETAILED_ACTIVITY: '/api/v1/user-management/activities',
        }
    }
};
